# Generated by Django 4.1 on 2022-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregableAPP', '0002_familiares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
    ]
