# Generated by Django 4.1 on 2022-09-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregableAPP', '0003_rename_camada_curso_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Empleado',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
