# Generated by Django 4.1 on 2022-09-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregableAPP', '0004_clientes_rename_estudiante_empleado_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevos_Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
